<a href="https://colab.research.google.com/github/yashsn/indian-sign-language/blob/master/Copy_of_LSTM_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://github.com/cynicphoenix/Human-Action-Recognition/blob/master/Phase1Evaluation.ipynb
Link for the implementation 

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')


Mounted at /content/gdrive


In [ ]:
import cv2     # for capturing videos
import math   # for mathematical operations
import matplotlib.pyplot as plt    # for plotting the images
%matplotlib inline
import pandas as pd
from keras.preprocessing import image   # for preprocessing the images
import numpy as np    # for mathematical operations
from keras.utils import np_utils
from skimage.transform import resize   # for resizing images
from sklearn.model_selection import train_test_split
from glob import glob
from tqdm import tqdm

In [ ]:
f = open("/content/gdrive/My Drive/Tp/aass.txt", "r")
temp = f.read()
videos = temp.split('\n')

# creating a dataframe having video names
train = pd.DataFrame()
train['video_name'] = videos
# train = train[:-1] 
# # here above line comment
train

video_name
0   morning/morning*a.mp4 1
1   morning/morning*e.mp4 1
2       think/think*b.mp4 2
3       think/think*f.mp4 2
4               i/i*c.mp4 3
5               i/i*g.mp4 3
6         good/good*d.mp4 4
7         good/good*h.mp4 4
8                 i/i*o.mp4
9         think/think*q.mp4
10    morning/morning*r.mp4
11          good/good*i.mp4
12        think/think*j.mp4

In [ ]:
train_video_tag = []
for i in range(train.shape[0]):
    train_video_tag.append(train['video_name'][i].split('/')[0])
    
train['tag'] = train_video_tag

In [ ]:
train

video_name      tag
0   morning/morning*a.mp4 1  morning
1   morning/morning*e.mp4 1  morning
2       think/think*b.mp4 2    think
3       think/think*f.mp4 2    think
4               i/i*c.mp4 3        i
5               i/i*g.mp4 3        i
6         good/good*d.mp4 4     good
7         good/good*h.mp4 4     good
8                 i/i*o.mp4        i
9         think/think*q.mp4    think
10    morning/morning*r.mp4  morning
11          good/good*i.mp4     good
12        think/think*j.mp4    think

In [ ]:
for i in tqdm(range(train.shape[0])):
    count = 0
    videoFile = train['video_name'][i]
    cap = cv2.VideoCapture('/content/gdrive/My Drive/Tp/'+videoFile.split('/')[1].split(' ')[0].split('*')[1])   # capturing the video from the given path
    frameRate = cap.get(5) #frame rate
    x=1
    # print(videoFile.split('/')[1].split(' ')[0])
    # print(cap)
    print("hio "+'/content/gdrive/My Drive/Tp/'+videoFile.split('/')[1].split(' ')[0].split('*')[1])
    while(cap.isOpened()):
        # print("yozzz")
        frameId = cap.get(1) #current frame number
        ret, frame = cap.read()
        if (ret != True):
            break
        if (frameId % math.floor(frameRate) == 0):
            # storing the frames in a new folder named train_1
            print('ere '+videoFile.split('/')[1].split(' ')[0].split('.')[0])
            filename ='/content/gdrive/My Drive/Tp/train/'+videoFile.split('/')[1].split(' ')[0].split('.')[0] +"_frame%d.jpg" % count;count+=1
            cv2.imwrite(filename, frame)
    cap.release()

  0%|          | 0/13 [00:00<?, ?it/s]

hio /content/gdrive/My Drive/Tp/a.mp4
ere morning*a
ere morning*a
ere morning*a


  8%|▊         | 1/13 [00:05<01:10,  5.87s/it]

hio /content/gdrive/My Drive/Tp/e.mp4
ere morning*e
ere morning*e
ere morning*e
ere morning*e


 15%|█▌        | 2/13 [00:11<01:04,  5.89s/it]

hio /content/gdrive/My Drive/Tp/b.mp4
ere think*b
ere think*b
ere think*b
ere think*b


 23%|██▎       | 3/13 [00:17<00:58,  5.84s/it]

hio /content/gdrive/My Drive/Tp/f.mp4
ere think*f
ere think*f
ere think*f
ere think*f


 31%|███       | 4/13 [00:23<00:53,  5.94s/it]

hio /content/gdrive/My Drive/Tp/c.mp4
ere i*c
ere i*c
ere i*c
ere i*c
ere i*c
ere i*c


 38%|███▊      | 5/13 [00:33<00:56,  7.11s/it]

hio /content/gdrive/My Drive/Tp/g.mp4
ere i*g
ere i*g
ere i*g
ere i*g
ere i*g


 46%|████▌     | 6/13 [00:40<00:49,  7.07s/it]

hio /content/gdrive/My Drive/Tp/d.mp4
ere good*d
ere good*d
ere good*d
ere good*d


 54%|█████▍    | 7/13 [00:47<00:42,  7.07s/it]

hio /content/gdrive/My Drive/Tp/h.mp4
ere good*h
ere good*h
ere good*h


 62%|██████▏   | 8/13 [00:52<00:31,  6.37s/it]

hio /content/gdrive/My Drive/Tp/o.mp4
ere i*o
ere i*o
ere i*o


 69%|██████▉   | 9/13 [00:55<00:21,  5.35s/it]

hio /content/gdrive/My Drive/Tp/q.mp4
ere think*q
ere think*q
ere think*q
ere think*q


 77%|███████▋  | 10/13 [00:58<00:14,  4.79s/it]

hio /content/gdrive/My Drive/Tp/r.mp4
ere morning*r
ere morning*r
ere morning*r
ere morning*r


 85%|████████▍ | 11/13 [01:02<00:08,  4.44s/it]

hio /content/gdrive/My Drive/Tp/i.mp4
ere good*i
ere good*i
ere good*i


 92%|█████████▏| 12/13 [01:05<00:03,  3.92s/it]

hio /content/gdrive/My Drive/Tp/j.mp4
ere think*j
ere think*j
ere think*j
ere think*j


100%|██████████| 13/13 [01:08<00:00,  5.28s/it]


For test--------------------------------

In [ ]:
# open the .txt file which have names of test videos
f = open("/content/gdrive/My Drive/Tp/aass2.txt", "r")

temp = f.read()
print(temp)
videos = temp.split('\n')

# creating a dataframe having video names
test = pd.DataFrame()
test['video_name'] = videos

test.head()
test_video_tag = []
print(test.shape[0])
for i in range(test.shape[0]):
    print("yo")
    test_video_tag.append(test['video_name'][i].split('/')[0])
    
test['tag'] = test_video_tag
test.head()

think/think*k.mp4
good/good*m.mp4
i/i*n.mp4
morning/morning*p.mp4
i/i*aa.mp4
think/think*bb.mp4
morning/morning*cc.mp4
7
yo
yo
yo
yo
yo
yo
yo


video_name      tag
0      think/think*k.mp4    think
1        good/good*m.mp4     good
2              i/i*n.mp4        i
3  morning/morning*p.mp4  morning
4             i/i*aa.mp4        i

Done here

In [ ]:

# getting the names of all the images
images = glob("/content/gdrive/My Drive/Tp/train/*.jpg")
train_image = []
train_class = []
# print(images[0].split('/')[1])
# print(images[0].split('/')[1].split('_')[1])
for i in tqdm(range(len(images))):
    # creating the image name
    train_image.append(images[i])
    # creating the class of image
    train_class.append(images[i].split('_')[0].split('*')[0].split('/')[6])
    
# storing the images and their class in a dataframe
train_data = pd.DataFrame()
train_data['image'] = train_image
train_data['class'] = train_class

# converting the dataframe into csv file 
train_data.to_csv('/content/gdrive/My Drive/Tp/train_new2.csv',header=True, index=False)
import keras
from keras.models import Sequential
from keras.applications.vgg16 import VGG16
from keras.layers import Dense, InputLayer, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D, GlobalMaxPooling2D
from keras.preprocessing import image
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tqdm import tqdm
from sklearn.model_selection import train_test_split

100%|██████████| 51/51 [00:00<00:00, 19114.42it/s]


In [ ]:
train = pd.read_csv('/content/gdrive/My Drive/Tp/train_new2.csv')
train

image    class
0   /content/gdrive/My Drive/Tp/train/morning*a_fr...  morning
1   /content/gdrive/My Drive/Tp/train/morning*a_fr...  morning
2   /content/gdrive/My Drive/Tp/train/morning*a_fr...  morning
3   /content/gdrive/My Drive/Tp/train/morning*e_fr...  morning
4   /content/gdrive/My Drive/Tp/train/morning*e_fr...  morning
5   /content/gdrive/My Drive/Tp/train/morning*e_fr...  morning
6   /content/gdrive/My Drive/Tp/train/morning*e_fr...  morning
7   /content/gdrive/My Drive/Tp/train/think*b_fram...    think
8   /content/gdrive/My Drive/Tp/train/think*b_fram...    think
9   /content/gdrive/My Drive/Tp/train/think*b_fram...    think
10  /content/gdrive/My Drive/Tp/train/think*b_fram...    think
11  /content/gdrive/My Drive/Tp/train/think*f_fram...    think
12  /content/gdrive/My Drive/Tp/train/think*f_fram...    think
13  /content/gdrive/My Drive/Tp/train/think*f_fram...    think
14  /content/gdrive/My Drive/Tp/train/think*f_fram...    think
15   /content/gdrive/My Drive/Tp/train/i*c_frame1.jpg        i
16   /content/gdrive/My Drive/Tp/train/i*c_frame0.jpg        i
17   /content/gdrive/My Drive/Tp/train/i*c_frame2.jpg        i
18   /content/gdrive/My Drive/Tp/train/i*c_frame3.jpg        i
19   /content/gdrive/My Drive/Tp/train/i*c_frame4.jpg        i
20   /content/gdrive/My Drive/Tp/train/i*c_frame5.jpg        i
21   /content/gdrive/My Drive/Tp/train/i*g_frame1.jpg        i
22   /content/gdrive/My Drive/Tp/train/i*g_frame0.jpg        i
23   /content/gdrive/My Drive/Tp/train/i*g_frame2.jpg        i
24   /content/gdrive/My Drive/Tp/train/i*g_frame3.jpg        i
25   /content/gdrive/My Drive/Tp/train/i*g_frame4.jpg        i
26  /content/gdrive/My Drive/Tp/train/good*d_frame...     good
27  /content/gdrive/My Drive/Tp/train/good*d_frame...     good
28  /content/gdrive/My Drive/Tp/train/good*d_frame...     good
29  /content/gdrive/My Drive/Tp/train/good*d_frame...     good
30  /content/gdrive/My Drive/Tp/train/good*h_frame...     good
31  /content/gdrive/My Drive/Tp/train/good*h_frame...     good
32  /content/gdrive/My Drive/Tp/train/good*h_frame...     good
33   /content/gdrive/My Drive/Tp/train/i*o_frame0.jpg        i
34   /content/gdrive/My Drive/Tp/train/i*o_frame1.jpg        i
35   /content/gdrive/My Drive/Tp/train/i*o_frame2.jpg        i
36  /content/gdrive/My Drive/Tp/train/think*q_fram...    think
37  /content/gdrive/My Drive/Tp/train/think*q_fram...    think
38  /content/gdrive/My Drive/Tp/train/think*q_fram...    think
39  /content/gdrive/My Drive/Tp/train/think*q_fram...    think
40  /content/gdrive/My Drive/Tp/train/morning*r_fr...  morning
41  /content/gdrive/My Drive/Tp/train/morning*r_fr...  morning
42  /content/gdrive/My Drive/Tp/train/morning*r_fr...  morning
43  /content/gdrive/My Drive/Tp/train/morning*r_fr...  morning
44  /content/gdrive/My Drive/Tp/train/good*i_frame...     good
45  /content/gdrive/My Drive/Tp/train/good*i_frame...     good
46  /content/gdrive/My Drive/Tp/train/good*i_frame...     good
47  /content/gdrive/My Drive/Tp/train/think*j_fram...    think
48  /content/gdrive/My Drive/Tp/train/think*j_fram...    think
49  /content/gdrive/My Drive/Tp/train/think*j_fram...    think
50  /content/gdrive/My Drive/Tp/train/think*j_fram...    think

In [ ]:
import keras
from keras.models import Sequential
from keras.applications.vgg16 import VGG16
from keras.layers import Dense, InputLayer, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D, GlobalMaxPooling2D
from keras.preprocessing import image
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tqdm import tqdm
from sklearn.model_selection import train_test_split

# creating an empty list
train_image = []

# for loop to read and store frames
for i in tqdm(range(train.shape[0])):
    # loading the image and keeping the target size as (224,224,3)
    img = image.load_img(train['image'][i], target_size=(224,224,3))
    # converting it to array
    img = image.img_to_array(img)
    # normalizing the pixel value
    img = img/255
    # appending the image to the train_image list
    train_image.append(img)
    
# converting the list to numpy array
X = np.array(train_image)

# shape of the array
X.shape

100%|██████████| 51/51 [00:01<00:00, 37.20it/s]


(51, 224, 224, 3)

In [ ]:
y = train['class']

# creating the training and validation set
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.2, stratify = y)

In [ ]:
# creating dummies of target variable for train and validation set
y_train = pd.get_dummies(y_train)
y_test = pd.get_dummies(y_test)

In [ ]:
base_model = VGG16(weights='imagenet', include_top=False)

58892288/58889256 [==============================] - 1s 0us/step


In [ ]:
X_train = base_model.predict(X_train)
X_train.shape

(40, 7, 7, 512)

In [ ]:
X_test = base_model.predict(X_test)
X_test.shape

(11, 7, 7, 512)

In [ ]:
X_train = X_train.reshape(X_train.shape[0], 49,512)
X_test = X_test.reshape(X_test.shape[0], 49,512)

In [ ]:
max = X_train.max()
X_train = X_train/max
X_test = X_test/max

X_train.shape

(40, 49, 512)

In [ ]:
from keras.layers import Dense,LSTM,Dropout
model = Sequential()



model.add(keras.layers.LSTM(512, input_shape=(X_train.shape[1:]), return_sequences=True))
model.add(keras.layers.LSTM(256))

model.add(keras.layers.Dense(64, activation='relu'))
model.add(keras.layers.Dropout(0.3))

# output layer
model.add(keras.layers.Dense(4, activation='softmax'))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, 49, 512)           2099200   
_________________________________________________________________
lstm_1 (LSTM)                (None, 256)               787456    
_________________________________________________________________
dense (Dense)                (None, 64)                16448     
_________________________________________________________________
dropout (Dropout)            (None, 64)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 4)                 260       
Total params: 2,903,364
Trainable params: 2,903,364
Non-trainable params: 0
_________________________________________________________________


In [ ]:
from keras.callbacks import ModelCheckpoint
mcp_save = ModelCheckpoint('weight.hdf5', save_best_only=True, monitor='val_loss', mode='min')

In [ ]:
model.compile(loss='categorical_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [ ]:
# model.fit(X_train, y_train, epochs=50, validation_data=(X_test, y_test), callbacks=[mcp_save] ,batch_size=32)
# zee=X_train.reshape(1,2,3)
# model.fit(X_train, y_train, epochs=60, validation_data=(X_test, y_test) , callbacks=[mcp_save],batch_size=32)
model.fit(X_train, y_train, epochs=60, validation_data=(X_test, y_test) ,batch_size=32)

Epoch 1/60
2/2 [==============================] - 1s 712ms/step - loss: 1.4126 - accuracy: 0.2000 - val_loss: 1.3977 - val_accuracy: 0.1818
Epoch 2/60
2/2 [==============================] - 1s 485ms/step - loss: 1.3912 - accuracy: 0.2500 - val_loss: 1.3678 - val_accuracy: 0.3636
Epoch 3/60
2/2 [==============================] - 1s 488ms/step - loss: 1.3991 - accuracy: 0.2500 - val_loss: 1.3587 - val_accuracy: 0.3636
Epoch 4/60
2/2 [==============================] - 1s 649ms/step - loss: 1.3813 - accuracy: 0.2750 - val_loss: 1.3574 - val_accuracy: 0.3636
Epoch 5/60
2/2 [==============================] - 1s 487ms/step - loss: 1.3548 - accuracy: 0.3250 - val_loss: 1.3522 - val_accuracy: 0.3636
Epoch 6/60
2/2 [==============================] - 1s 651ms/step - loss: 1.3837 - accuracy: 0.3250 - val_loss: 1.3566 - val_accuracy: 0.3636
Epoch 7/60
2/2 [==============================] - 1s 635ms/step - loss: 1.3524 - accuracy: 0.2750 - val_loss: 1.3495 - val_accuracy: 0.3636
Epoch 8/60
2/2 [====

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.preprocessing import image
import numpy as np
import pandas as pd
from tqdm import tqdm
from keras.applications.vgg16 import VGG16
import cv2
import math
import os
from glob import glob
from scipy import stats as s
base_model = VGG16(weights='imagenet', include_top=False)

In [ ]:
# model.load_weights("weight.hdf5")

In [ ]:
model.compile(loss='categorical_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [ ]:
f = open("/content/gdrive/My Drive/Tp/aass2.txt", "r")
temp = f.read()
videos = temp.split('\n')

# creating the dataframe
test = pd.DataFrame()
test['video_name'] = videos

test_videos = test['video_name']
test

video_name
0       think/think*k.mp4
1         good/good*m.mp4
2               i/i*n.mp4
3   morning/morning*p.mp4
4              i/i*aa.mp4
5      think/think*bb.mp4
6  morning/morning*cc.mp4

In [ ]:
train = pd.read_csv('/content/gdrive/My Drive/Tp/train_new2.csv')
y = train['class']
y = pd.get_dummies(y)

In [ ]:
y

good  i  morning  think
0      0  0        1      0
1      0  0        1      0
2      0  0        1      0
3      0  0        1      0
4      0  0        1      0
5      0  0        1      0
6      0  0        1      0
7      0  0        0      1
8      0  0        0      1
9      0  0        0      1
10     0  0        0      1
11     0  0        0      1
12     0  0        0      1
13     0  0        0      1
14     0  0        0      1
15     0  1        0      0
16     0  1        0      0
17     0  1        0      0
18     0  1        0      0
19     0  1        0      0
20     0  1        0      0
21     0  1        0      0
22     0  1        0      0
23     0  1        0      0
24     0  1        0      0
25     0  1        0      0
26     1  0        0      0
27     1  0        0      0
28     1  0        0      0
29     1  0        0      0
30     1  0        0      0
31     1  0        0      0
32     1  0        0      0
33     0  1        0      0
34     0  1        0      0
35     0  1        0      0
36     0  0        0      1
37     0  0        0      1
38     0  0        0      1
39     0  0        0      1
40     0  0        1      0
41     0  0        1      0
42     0  0        1      0
43     0  0        1      0
44     1  0        0      0
45     1  0        0      0
46     1  0        0      0
47     0  0        0      1
48     0  0        0      1
49     0  0        0      1
50     0  0        0      1

Use probablity here sigmoid 

In [ ]:
files = glob("/content/gdrive/My Drive/Tp/test/*.jpg")
for f in files:
  os.remove(f)

In [ ]:
predict = []
actual = []
from sklearn.metrics import accuracy_score
print("shape is",test_videos.shape[0])
# for loop to extract frames from each test video
for i in tqdm(range(test_videos.shape[0])):
    count = 0
    videoFile = test_videos[i]
    
    cap = cv2.VideoCapture('/content/gdrive/My Drive/Tp/'+videoFile.split('/')[1].split(' ')[0].split('*')[1])   # capturing the video from the given path
    frameRate = cap.get(5) #frame rate
    x=1
    # removing all other files from the test folder
    files = glob("/content/gdrive/My Drive/Tp/test/*.jpg")
    for f in files:
        os.remove(f)
    while(cap.isOpened()):
        frameId = cap.get(1) #current frame number
        ret, frame = cap.read()
        if (ret != True):
            break
        if (frameId % math.floor(frameRate) == 0):
            # storing the frames of this particular video in temp folder
            filename ='/content/gdrive/My Drive/Tp/test/'+videoFile.split('/')[1].split(' ')[0].split('.')[0] +"_frame%d.jpg" % count;count+=1
            
            cv2.imwrite(filename, frame)
    cap.release()
    print(predict)
    # reading all the frames from temp folder
    images = glob("/content/gdrive/My Drive/Tp/test/*.jpg")
    print(images)
    prediction_images = []
    for i in range(len(images)):
        img = image.load_img(images[i], target_size=(224,224,3))
        img = image.img_to_array(img)
        img = img/255
        prediction_images.append(img)
       
    # converting all the frames for a test video into numpy array
    prediction_images = np.array(prediction_images)
    # extracting features using pre-trained model
    prediction_images = base_model.predict(prediction_images)
    # converting features in one dimensional array
    prediction_images = prediction_images.reshape(prediction_images.shape[0], 49,512)
    # print(prediction_images)
    # predicting tags for each array
    prediction=[]
    print("pred img shape",prediction_images.shape)
    prediction = model.predict_classes(prediction_images)
    print(prediction)
    # appending the mode of predictions in predict list to assign the tag to the video
    print("hi",y.columns.values[1])
    predict.append(y.columns.values[s.mode(prediction)[0][0]])
    # appending the actual tag of the video
    print(videoFile)
    actual.append(videoFile.split('/')[0])
    print("hereee")
    print(predict)
    print("------------------------")
    print("this is",accuracy_score(predict, actual)*100)

  0%|          | 0/7 [00:00<?, ?it/s]

shape is 7
[]
['/content/gdrive/My Drive/Tp/test/think*k_frame0.jpg', '/content/gdrive/My Drive/Tp/test/think*k_frame1.jpg', '/content/gdrive/My Drive/Tp/test/think*k_frame2.jpg']
pred img shape (3, 49, 512)
Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


 14%|█▍        | 1/7 [00:03<00:19,  3.32s/it]

[1 1 1]
hi i
think/think*k.mp4
hereee
['i']
------------------------
this is 0.0
['i']
['/content/gdrive/My Drive/Tp/test/good*m_frame0.jpg', '/content/gdrive/My Drive/Tp/test/good*m_frame1.jpg', '/content/gdrive/My Drive/Tp/test/good*m_frame2.jpg', '/content/gdrive/My Drive/Tp/test/good*m_frame3.jpg']


 29%|██▊       | 2/7 [00:06<00:16,  3.21s/it]

pred img shape (4, 49, 512)
[1 1 1 1]
hi i
good/good*m.mp4
hereee
['i', 'i']
------------------------
this is 0.0
['i', 'i']
['/content/gdrive/My Drive/Tp/test/i*n_frame0.jpg', '/content/gdrive/My Drive/Tp/test/i*n_frame1.jpg', '/content/gdrive/My Drive/Tp/test/i*n_frame2.jpg']


 43%|████▎     | 3/7 [00:08<00:11,  2.97s/it]

pred img shape (3, 49, 512)
[1 1 1]
hi i
i/i*n.mp4
hereee
['i', 'i', 'i']
------------------------
this is 33.33333333333333
['i', 'i', 'i']
['/content/gdrive/My Drive/Tp/test/morning*p_frame0.jpg', '/content/gdrive/My Drive/Tp/test/morning*p_frame1.jpg', '/content/gdrive/My Drive/Tp/test/morning*p_frame2.jpg', '/content/gdrive/My Drive/Tp/test/morning*p_frame3.jpg']


 57%|█████▋    | 4/7 [00:11<00:08,  2.92s/it]

pred img shape (4, 49, 512)
[1 1 1 1]
hi i
morning/morning*p.mp4
hereee
['i', 'i', 'i', 'i']
------------------------
this is 25.0
['i', 'i', 'i', 'i']
['/content/gdrive/My Drive/Tp/test/i*aa_frame0.jpg', '/content/gdrive/My Drive/Tp/test/i*aa_frame1.jpg']


 71%|███████▏  | 5/7 [00:14<00:05,  2.82s/it]

pred img shape (2, 49, 512)
[1 1]
hi i
i/i*aa.mp4
hereee
['i', 'i', 'i', 'i', 'i']
------------------------
this is 40.0
['i', 'i', 'i', 'i', 'i']
['/content/gdrive/My Drive/Tp/test/think*bb_frame0.jpg', '/content/gdrive/My Drive/Tp/test/think*bb_frame1.jpg', '/content/gdrive/My Drive/Tp/test/think*bb_frame2.jpg']


 86%|████████▌ | 6/7 [00:17<00:02,  2.98s/it]

pred img shape (3, 49, 512)
[1 1 1]
hi i
think/think*bb.mp4
hereee
['i', 'i', 'i', 'i', 'i', 'i']
------------------------
this is 33.33333333333333
['i', 'i', 'i', 'i', 'i', 'i']
['/content/gdrive/My Drive/Tp/test/morning*cc_frame0.jpg', '/content/gdrive/My Drive/Tp/test/morning*cc_frame1.jpg', '/content/gdrive/My Drive/Tp/test/morning*cc_frame2.jpg']


100%|██████████| 7/7 [00:20<00:00,  2.97s/it]

pred img shape (3, 49, 512)
[1 1 1]
hi i
morning/morning*cc.mp4
hereee
['i', 'i', 'i', 'i', 'i', 'i', 'i']
------------------------
this is 28.57142857142857
